---
kind: Service
apiVersion: v1
metadata:
  name: talent-api
  namespace: crecimiento-develop
  labels:
    app: talent-api
spec:
  selector:
    app: talent-api
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
