---
kind: Service
apiVersion: v1
metadata:
  name: vacaciones-api
  namespace: BRANCH_NAME
  labels:
    app: vacaciones-api
spec:
  selector:
    app: vacaciones-api
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 9010
      targetPort: 9010
